### ISSUE TITLE
console-command-on-exit executed hundreds of times?

### ISSUE THREAD

**Issue by EvilOlaf** [isokissa3/WorldGuardExtraFlagsPlugin#10]
Hey there,
I recently tried to add a `minecraft:tp` command to teleport players on exiting the region. It kind a worked. However I wondered why it took a moment until the teleport was issued.

`/rg flag theregion console-command-on-exit /minecraft:tp %username% 12 65 -100`

A look at the logs showed me this:
```
[...]
       at sun.reflect.GeneratedMethodAccessor183.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:498) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.CommandTp.execute(CommandTp.java:88) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:108) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:43) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.goldtreeservers.worldguardextraflags.flags.handlers.ConsoleCommandOnExitFlag.onCrossBoundary(ConsoleCommandOnExitFlag.java:72) ~[?:?]
        at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:217) ~[?:?]
        at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:177) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerTeleport(WorldGuardPlayerListener.java:366) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor183.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:498) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.CommandTp.execute(CommandTp.java:88) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:108) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:43) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.goldtreeservers.worldguardextraflags.flags.handlers.ConsoleCommandOnExitFlag.onCrossBoundary(ConsoleCommandOnExitFlag.java:72) ~[?:?]
        at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:217) ~[?:?]
        at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:177) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerTeleport(WorldGuardPlayerListener.java:366) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor183.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:498) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.CommandTp.execute(CommandTp.java:88) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:108) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:43) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
[21:48:28] [Server thread/INFO]: Teleported ThePlayer to 12.5, 65.0, -100.5
[21:48:28] [Server thread/INFO]: Teleported ThePlayer to 12.5, 65.0, -100.5
[21:48:28] [Server thread/INFO]: Teleported ThePlayer to 12.5, 65.0, -100.5
[21:48:28] [Server thread/INFO]: Teleported ThePlayer to 12.5, 65.0, -100.5
[21:48:28] [Server thread/INFO]: Teleported ThePlayer to 12.5, 65.0, -100.5
[21:48:28] [Server thread/INFO]: Teleported ThePlayer to 12.5, 65.0, -100.5
[21:48:28] [Server thread/INFO]: Teleported ThePlayer to 12.5, 65.0, -100.5
[21:48:28] [Server thread/INFO]: Teleported ThePlayer to 12.5, 65.0, -100.5
[21:48:28] [Server thread/INFO]: Teleported ThePlayer to 12.5, 65.0, -100.5
[21:48:28] [Server thread/INFO]: Teleported ThePlayer to 12.5, 65.0, -100.5
[21:48:28] [Server thread/INFO]: Teleported ThePlayer to 12.5, 65.0, -100.5
[21:48:28] [Server thread/INFO]: Teleported ThePlayer to 12.5, 65.0, -100.5
[21:48:28] [Server thread/INFO]: Teleported ThePlayer to 12.5, 65.0, -100.5
[21:48:28] [Server thread/INFO]: Teleported ThePlayer to 12.5, 65.0, -100.5
[...]
```

This is just a very small part of the whole log as it  looked like the errors repeating themselves. Did not read out more than 3000 lines.
Using the same command with `console-command-on-entry` working well.

Using the build from here: https://github.com/isokissa3/WorldGuardExtraFlagsPlugin/issues/6#issuecomment-317799112

**Comment by isokissa3** [comment]
Teleport commands are not supported, use teleport-on-entry
