### ISSUE TITLE
[WorldGuardExtraFlags] Unhandled exception occured in onPacketSending(PacketEvent) for WorldGuardExtraFlags

### ISSUE THREAD

**Issue by SrBedrock** [isokissa3/WorldGuardExtraFlagsPlugin#101]
```[17:57:29 INFO]: AlexGalaxy200 lost connection: AVISO! Tempo limite de sessão excedido, você foi expulso do servidor, por favor, tente novamente!
[17:57:32 ERROR]: [WorldGuardExtraFlags] Unhandled exception occured in onPacketSending(PacketEvent) for WorldGuardExtraFlags
java.lang.UnsupportedOperationException: The method isValid is not supported for temporary players.
at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[?:?]
at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$fc5f3c7.isValid(<generated>) ~[?:?]
at net.goldtreeservers.worldguardextraflags.protocollib.RemoveEffectPacketListener.onPacketSending(RemoveEffectPacketListener.java:26) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:200) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:169) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1525) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1498) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.EntityPlayer.b(EntityPlayer.java:1470) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.EntityLiving.tickPotionEffects(EntityLiving.java:663) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:337) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:370) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2286) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:165) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:426) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:146) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1255) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-240]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[17:57:32 ERROR]: Parameters:
net.minecraft.server.v1_14_R1.PacketPlayOutRemoveEntityEffect@7b1aab1e[
a=91
b=net.minecraft.server.v1_14_R1.MobEffectList@2a225dd7```

**Comment by isokissa3** [comment]
The issue is somewhere else, temporary players are used only during login (internals of ProtocolLib) and should not receive any game related packets.
