### ISSUE TITLE
Could not pass event PortalCreateEvent to WorldGuardExtraFlags

### ISSUE THREAD

**Issue by N0tMyFaultOG** [isokissa3/WorldGuardExtraFlagsPlugin#102]
I noticed the following stacktrace in my console today. It appears to happen if someone lights a a portal and the nether portal flag isn't set. Is it mandatory? I thought it would act like regular WorldGuard, if you don't set flags it doesn't do anything.
```
[16:32:08 ERROR]: Could not pass event PortalCreateEvent to WorldGuardExtraFlags v4.1.2
java.lang.NoSuchMethodError: org.bukkit.event.world.PortalCreateEvent.getBlocks()Ljava/util/ArrayList;
at net.goldtreeservers.worldguardextraflags.listeners.EntityListener.onPortalCreateEvent(EntityListener.java:24) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor648.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-62]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-62]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-62]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.BlockPortal$Shape.createPortal(BlockPortal.java:342) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.BlockPortal.a(BlockPortal.java:60) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.BlockFire.onPlace(BlockFire.java:308) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.ItemStack.placeItem(ItemStack.java:272) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:511) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1373) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1014) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:937) ~[patched_1.15.1.jar:git-Paper-62]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
WorldGuard version: 7.0.3-SNAPSHOT;2006-db3838c
WorldGuardExtraFlags version: 4.1.2

**Comment by isokissa3** [comment]
Fixed in 78add0a
