### ISSUE TITLE
GodStatusChangeEvent error

### ISSUE THREAD

**Issue by andris155** [isokissa3/WorldGuardExtraFlagsPlugin#27]
```
[13:57:38] [Server thread/INFO]: CommandBlock at -332,4,-490 issued server command: /god MrZero off
[13:57:38] [Server thread/ERROR]: Could not pass event GodStatusChangeEvent to WorldGuardExtraFlags v2.14.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1331]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1331]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1331]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1331]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1331]
	at com.earth2me.essentials.commands.Commandgod.togglePlayer(Commandgod.java:34) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.EssentialsToggleCommand.toggleOtherPlayers(EssentialsToggleCommand.java:64) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.Commandgod.run(Commandgod.java:18) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:167) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:517) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:432) [EssentialsX-2.0.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [patched_1.12.2.jar:git-Paper-1331]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.CommandBlockListenerAbstract.executeCommand(CommandBlockListenerAbstract.java:267) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.CommandBlockListenerAbstract.executeSafely(CommandBlockListenerAbstract.java:166) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:121) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.BlockCommand.a(BlockCommand.java:95) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.BlockCommand.b(BlockCommand.java:81) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:786) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:317) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:898) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1331]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at net.goldtreeservers.worldguardextraflags.listeners.EssentialsListener.onGodStatusChangeEvent(EssentialsListener.java:17) ~[WorldGuardExtraFlagsPlugin.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor510.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1331]
	... 24 more
```

```
[12:05:59] [Server thread/INFO]: CONSOLE issued server command: /god MrBoss99 off
[12:05:59] [Server thread/ERROR]: Could not pass event GodStatusChangeEvent to WorldGuardExtraFlags v2.14.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1331]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1331]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1331]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1331]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1331]
	at com.earth2me.essentials.commands.Commandgod.togglePlayer(Commandgod.java:34) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.EssentialsToggleCommand.toggleOtherPlayers(EssentialsToggleCommand.java:64) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.Commandgod.run(Commandgod.java:18) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:167) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:517) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:432) ~[EssentialsX-2.0.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1331]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1331]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:677) ~[patched_1.12.2.jar:git-Paper-1331]
	at net.goldtreeservers.worldguardextraflags.flags.handlers.ConsoleCommandOnEntryFlag.onCrossBoundary(ConsoleCommandOnEntryFlag.java:54) ~[WorldGuardExtraFlagsPlugin.jar:?]
	at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:217) ~[worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:177) ~[worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.bukkit.listener.PlayerMoveListener.onPlayerMove(PlayerMoveListener.java:79) ~[worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor561.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1331]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1331]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1331]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1331]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:692) ~[patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:88) ~[patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1331]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1331]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1331]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at net.goldtreeservers.worldguardextraflags.listeners.EssentialsListener.onGodStatusChangeEvent(EssentialsListener.java:17) ~[WorldGuardExtraFlagsPlugin.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor694.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1331]
	... 35 more
```

**Comment by isokissa3** [comment]
Fixed
