### ISSUE TITLE
PlayerSpawnLocationEvent error

### ISSUE THREAD

**Issue by andris155** [isokissa3/WorldGuardExtraFlagsPlugin#33]
```
[16:37:41] [User Authenticator #40/INFO]: UUID of player Csipeszto is f083b1e8-8c76-3e89-939f-390c5e460de3
[16:37:41] [Server thread/ERROR]: Could not pass event PlayerSpawnLocationEvent to WorldGuardExtraFlags v3.0.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1389]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1389]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1389]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1389]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1389]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:139) [patched_1.12.2.jar:git-Paper-1389]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) [patched_1.12.2.jar:git-Paper-1389]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) [patched_1.12.2.jar:git-Paper-1389]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:255) [patched_1.12.2.jar:git-Paper-1389]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.12.2.jar:git-Paper-1389]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:941) [patched_1.12.2.jar:git-Paper-1389]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1389]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1389]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1389]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[patched_1.12.2.jar:git-Paper-1389]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.12.2.jar:git-Paper-1389]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[patched_1.12.2.jar:git-Paper-1389]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[patched_1.12.2.jar:git-Paper-1389]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[patched_1.12.2.jar:git-Paper-1389]
	at com.sk89q.worldguard.session.SessionManager.get(SessionManager.java:253) ~[worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
	at net.goldtreeservers.worldguardextraflags.listeners.PlayerListener.onPlayerSpawnLocationEventMonitor(PlayerListener.java:237) ~[WorldGuardExtraFlagsPlugin.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor468.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1389]
	... 14 more
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_12_R1.EntityPlayer.setPlayerWeather(EntityPlayer.java:1443) ~[patched_1.12.2.jar:git-Paper-1389]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setPlayerWeather(CraftPlayer.java:881) ~[patched_1.12.2.jar:git-Paper-1389]
	at com.sk89q.worldguard.session.handler.WeatherLockFlag.updatePlayerWeather(WeatherLockFlag.java:50) ~[worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.session.handler.WeatherLockFlag.onInitialValue(WeatherLockFlag.java:59) ~[worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.session.handler.WeatherLockFlag.onInitialValue(WeatherLockFlag.java:32) ~[worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.session.handler.FlagValueChangeHandler.initialize(FlagValueChangeHandler.java:45) ~[worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.session.Session.initialize(Session.java:116) ~[worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.session.SessionManager.createSession(SessionManager.java:226) ~[worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.session.SessionManager.access$200(SessionManager.java:52) ~[worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.session.SessionManager$2.load(SessionManager.java:74) ~[worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
	at com.sk89q.worldguard.session.SessionManager$2.load(SessionManager.java:71) ~[worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[patched_1.12.2.jar:git-Paper-1389]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[patched_1.12.2.jar:git-Paper-1389]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[patched_1.12.2.jar:git-Paper-1389]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[patched_1.12.2.jar:git-Paper-1389]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.12.2.jar:git-Paper-1389]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[patched_1.12.2.jar:git-Paper-1389]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[patched_1.12.2.jar:git-Paper-1389]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[patched_1.12.2.jar:git-Paper-1389]
	at com.sk89q.worldguard.session.SessionManager.get(SessionManager.java:253) ~[worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
	at net.goldtreeservers.worldguardextraflags.listeners.PlayerListener.onPlayerSpawnLocationEventMonitor(PlayerListener.java:237) ~[WorldGuardExtraFlagsPlugin.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor468.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1389]
	... 14 more
```

**Comment by isokissa3** [comment]
Use 3.0.3
