### ISSUE TITLE
WorldEdit/WorldGuard breaking changes - New vector implementation.

### ISSUE THREAD

**Issue by mibby** [isokissa3/WorldGuardExtraFlagsPlugin#57]
@isokissa3 WorldGuardExtraFlags needs to be updated to work with the breaking changes in WorldEdit 7 & WorldGuard 7. A new vector method was implemented, replacing the old. All relevant Vector and BlockVector methods used needs to be swapped out with Vector3 and BlockVector3.

**Comment by andris155** [comment]
```
[08:12:43] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to WorldGuardExtraFlags v3.0.4
java.lang.NoClassDefFoundError: com/sk89q/worldedit/BlockVector
	at net.goldtreeservers.worldguardextraflags.listeners.WorldListener.onChunkUnloadEvent(WorldListener.java:39) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor857.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-429]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:439) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:401) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:298) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1088) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-429]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by isokissa3** [comment]
This will be done as soon as the vector update has been pushed to Bukkit as most people are going to use that version

**Comment by mibby** [comment]
@isokissa3 Would it be possible to get a dev build with the vector changes implemented in WGEF?
