### ISSUE TITLE
Error in Spigot 1.13.2.

### ISSUE THREAD

**Issue by TheIntelloBox** [isokissa3/WorldGuardExtraFlagsPlugin#61]
Hey ! :D

I have an error using Spigot 1.13.2: https://hastebin.com/vacugudata.cs ! :D

Thanks ! :D

**Comment by isokissa3** [comment]
WG version, WE version?

**Comment by Resi23** [comment]
Hi,
I have a similar problem. It spams the logfile,

`[13:26:38] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to WorldGuardExtraFlags v4.1.1
java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
	at net.goldtreeservers.worldguardextraflags.wg.wrappers.v7.WorldGuardSevenCommunicator.doUnloadChunkFlagCheck(WorldGuardSevenCommunicator.java:104) ~[?:?]
	at net.goldtreeservers.worldguardextraflags.listeners.WorldListener.onChunkUnloadEvent(WorldListener.java:34) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor595.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-459]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-459]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-459]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-459]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:439) ~[patched_1.13.2.jar:git-Paper-459]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:401) ~[patched_1.13.2.jar:git-Paper-459]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:298) ~[patched_1.13.2.jar:git-Paper-459]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1088) ~[patched_1.13.2.jar:git-Paper-459]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-459]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-459]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-459]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

I use FastAsyncWorldEdit-bukkit-18.11.21-99fb2b5-2072 from [here](FastAsyncWorldEdit-bukkit-18.11.21-99fb2b5-2072) and (FAWE) worldguard-legacy-7.0.0-SNAPSHOT-dist from [here](https://ci.athion.net/job/FAWE-WorldGuard-1.13/31/)

**Comment by Resi23** [comment]
Ok i use Version 4.1 of /WorldGuardExtraFlagsPlugin and all is fine :)
