### ISSUE TITLE
Fixed

### ISSUE THREAD

**Issue by CMCosMic** [isokissa3/WorldGuardExtraFlagsPlugin#67]
`[18:15:34 ERROR]: [WorldGuardExtraFlags] Unhandled exception occured in onPacketSending(PacketEvent) for WorldGuardExtraFlags
java.lang.NullPointerException: null
        at net.goldtreeservers.worldguardextraflags.protocollib.RemoveEffectPacketListener.onPacketSending(RemoveEffectPacketListener.java:36) ~[WorldGuardExtraFlags.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.4.0-b421]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1138) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.EntityPlayer.b(EntityPlayer.java:1116) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.EntityLiving.removeEffect(EntityLiving.java:732) [spigot.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.removePotionEffect(CraftLivingEntity.java:286) [spigot.jar:git-Spigot-642f6d2-6103339]
        at me.mrCookieSlime.PrisonUtils.PrisonUtils$1.run(PrisonUtils.java:86) [PrisonUtils_v1.7.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-642f6d2-6103339]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[18:15:34 ERROR]: Parameters:
  net.minecraft.server.v1_12_R1.PacketPlayOutRemoveEntityEffect@73d3997b[
    a=865
    b=net.minecraft.server.v1_12_R1.MobEffectList@1c9e07c6
  ]

[18:15:34 ERROR]: [WorldGuardExtraFlags] Unhandled exception occured in onPacketSending(PacketEvent) for WorldGuardExtraFlags
java.lang.NullPointerException: null
        at net.goldtreeservers.worldguardextraflags.protocollib.RemoveEffectPacketListener.onPacketSending(RemoveEffectPacketListener.java:36) ~[WorldGuardExtraFlags.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.4.0-b421]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1138) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.EntityPlayer.b(EntityPlayer.java:1116) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.EntityLiving.removeEffect(EntityLiving.java:732) [spigot.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.removePotionEffect(CraftLivingEntity.java:286) [spigot.jar:git-Spigot-642f6d2-6103339]
        at me.mrCookieSlime.PrisonUtils.PrisonUtils$1.run(PrisonUtils.java:86) [PrisonUtils_v1.7.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-642f6d2-6103339]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[18:15:34 ERROR]: Parameters:
  net.minecraft.server.v1_12_R1.PacketPlayOutRemoveEntityEffect@281b41ec[
    a=865
    b=net.minecraft.server.v1_12_R1.InstantMobEffect@4f668f29
  ]`

Running 1.12.2

**Comment by isokissa3** [comment]
Thats odd error, I would assume you have previous errors causing this? Could you send ur whole console output

**Comment by CMCosMic** [comment]
> Thats odd error, I would assume you have previous errors causing this? Could you send ur whole console output

https://pastebin.com/rXMpeFWG 

I didnt have the plugin at first, but then I reloaded the server and then the errors started coming in.

**Comment by CMCosMic** [comment]
After fixing some other errors, it seemed to be working. Sorry for the inconvenience!
