### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by niko411** [isokissa3/WorldGuardExtraFlagsPlugin#68]
[01:06:36] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to WorldGuardExtraFlags v4.1.2
java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
	at net.goldtreeservers.worldguardextraflags.wg.wrappers.v7.WorldGuardSevenCommunicator.doUnloadChunkFlagCheck(WorldGuardSevenCommunicator.java:108) ~[?:?]
	at net.goldtreeservers.worldguardextraflags.listeners.WorldListener.onChunkUnloadEvent(WorldListener.java:34) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor176.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-502]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-502]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-502]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-502]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:440) ~[patched_1.13.2.jar:git-Paper-502]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:402) ~[patched_1.13.2.jar:git-Paper-502]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:281) ~[patched_1.13.2.jar:git-Paper-502]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1083) ~[patched_1.13.2.jar:git-Paper-502]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-502]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-502]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-502]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[01:06:36] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to WorldGuardExtraFlags v4.1.2
java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
	at net.goldtreeservers.worldguardextraflags.wg.wrappers.v7.WorldGuardSevenCommunicator.doUnloadChunkFlagCheck(WorldGuardSevenCommunicator.java:108) ~[?:?]
	at net.goldtreeservers.worldguardextraflags.listeners.WorldListener.onChunkUnloadEvent(WorldListener.java:34) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor176.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-502]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-502]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-502]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-502]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:440) ~[patched_1.13.2.jar:git-Paper-502]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:402) ~[patched_1.13.2.jar:git-Paper-502]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:281) ~[patched_1.13.2.jar:git-Paper-502]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1083) ~[patched_1.13.2.jar:git-Paper-502]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-502]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-502]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-502]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by niko411** [comment]
[latest.log](https://github.com/isokissa3/WorldGuardExtraFlagsPlugin/files/2766274/latest.log)

**Comment by isokissa3** [comment]
Please update your WE & WG to the latest version
