### ISSUE TITLE
Not work with Fawe

### ISSUE THREAD

**Issue by andris155** [isokissa3/WorldGuardExtraFlagsPlugin#71]
```
[09:03:44] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to WorldGuardExtraFlags v4.1.2
java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
	at net.goldtreeservers.worldguardextraflags.wg.wrappers.v7.WorldGuardSevenCommunicator.doUnloadChunkFlagCheck(WorldGuardSevenCommunicator.java:108) ~[?:?]
	at net.goldtreeservers.worldguardextraflags.listeners.WorldListener.onChunkUnloadEvent(WorldListener.java:34) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor625.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-507]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-507]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-507]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-507]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:440) ~[patched_1.13.2.jar:git-Paper-507]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:402) ~[patched_1.13.2.jar:git-Paper-507]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:281) ~[patched_1.13.2.jar:git-Paper-507]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1083) ~[patched_1.13.2.jar:git-Paper-507]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-507]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-507]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-507]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.math.BlockVector3
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-507]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-507]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 15 more
```

**Comment by isokissa3** [comment]
Thats because FAWE has not updated to latest WE API, use 4.1.0 version of the plugin
