### ISSUE TITLE
Error caused by chunk unloading flag

### ISSUE THREAD

**Issue by Grisbal** [isokissa3/WorldGuardExtraFlagsPlugin#73]
Hello

There is following error in my console output:

[20:25:06 ERROR]: [WorldGuardExtraFlags] Plugin WorldGuardExtraFlags v4.1.2 has failed to register events for class net.goldtreeservers.worldguardextraflags.listeners.PlayerListener because org/spigotmc/event/player/PlayerSpawnLocationEvent does not exist.
[20:25:06 INFO]: Loading chunks for region spawn located in world due to chunk-unload flag being deny

[20:31:30 ERROR]: Failed to fetch mob spawner entity at (-263087353, 35, 256901148)
[20:33:17 ERROR]: Error occurred while enabling WorldGuardExtraFlags v4.1.2 (Is it up to date?)
net.minecraft.server.v1_13_R2.ReportedException: Exception generating new chunk
        at net.minecraft.server.v1_13_R2.ChunkProviderServer.a(ChunkProviderServer.java:170) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:113) ~[server.jar:git-Bukkit-b26fb37]
        at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.getChunkAt(CraftWorld.java:144) ~[server.jar:git-Bukkit-b26fb37]
        at net.goldtreeservers.worldguardextraflags.wg.wrappers.v7.WorldGuardSevenCommunicator.doUnloadChunkFlagCheck(WorldGuardSevenCommunicator.java:98) ~[?:?]
        at net.goldtreeservers.worldguardextraflags.WorldGuardExtraFlagsPlugin.onEnable(WorldGuardExtraFlagsPlugin.java:175) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[server.jar:git-Bukkit-b26fb37]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [server.jar:git-Bukkit-b26fb37]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [server.jar:git-Bukkit-b26fb37]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:423) [server.jar:git-Bukkit-b26fb37]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:349) [server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:571) [server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:533) [server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:411) [server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:270) [server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:676) [server.jar:git-Bukkit-b26fb37]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.util.concurrent.CompletionException: com.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_201]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.thenApplyAsync(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.Map.computeIfAbsent(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.Map.computeIfAbsent(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:53) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:27) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.Map.computeIfAbsent(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.Map.computeIfAbsent(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.Map.computeIfAbsent(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.Map.computeIfAbsent(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:115) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:61) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_201]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.concurrent.CompletableFuture.asyncSupplyStage(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.supplyAsync(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.SchedulerBatch.a(SourceFile:39) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:108) ~[server.jar:git-Bukkit-b26fb37]
        ... 14 more
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215) ~[server.jar:git-Bukkit-b26fb37]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[server.jar:git-Bukkit-b26fb37]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[server.jar:git-Bukkit-b26fb37]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[server.jar:git-Bukkit-b26fb37]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.BiomeCache.a(SourceFile:44) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.BiomeCache.a(SourceFile:48) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.WorldChunkManagerOverworld.getBiome(SourceFile:103) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkGeneratorAbstract.addFeatures(SourceFile:60) ~[server.jar:git-Bukkit-b26fb37]
        at org.bukkit.craftbukkit.v1_13_R2.generator.NormalChunkGenerator.addFeatures(NormalChunkGenerator.java:52) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkTaskCarve.a(SourceFile:13) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkTask.a(SourceFile:35) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:95) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:75) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:1) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_201]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.thenApplyAsync(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.Map.computeIfAbsent(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.Map.computeIfAbsent(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:53) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus$1.a(SourceFile:27) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.Map.computeIfAbsent(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.Map.computeIfAbsent(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.Map.computeIfAbsent(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.Map.computeIfAbsent(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:115) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:61) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_201]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.concurrent.CompletableFuture.asyncSupplyStage(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.supplyAsync(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.SchedulerBatch.a(SourceFile:39) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:108) ~[server.jar:git-Bukkit-b26fb37]
        ... 14 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at net.minecraft.server.v1_13_R2.GenLayer.a(SourceFile:20) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.WorldChunkManagerOverworld.a(SourceFile:117) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.BiomeCache$a.<init>(SourceFile:22) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.BiomeCache$1.load(SourceFile:33) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.BiomeCache$1.load(SourceFile:30) ~[server.jar:git-Bukkit-b26fb37]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[server.jar:git-Bukkit-b26fb37]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[server.jar:git-Bukkit-b26fb37]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[server.jar:git-Bukkit-b26fb37]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[server.jar:git-Bukkit-b26fb37]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[server.jar:git-Bukkit-b26fb37]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[server.jar:git-Bukkit-b26fb37]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[server.jar:git-Bukkit-b26fb37]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.BiomeCache.a(SourceFile:44) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.BiomeCache.a(SourceFile:48) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.WorldChunkManagerOverworld.getBiome(SourceFile:103) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkGeneratorAbstract.addFeatures(SourceFile:60) ~[server.jar:git-Bukkit-b26fb37]
        at org.bukkit.craftbukkit.v1_13_R2.generator.NormalChunkGenerator.addFeatures(NormalChunkGenerator.java:52) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkTaskCarve.a(SourceFile:13) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkTask.a(SourceFile:35) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:95) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:75) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:1) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.Scheduler$a$$Lambda$1984/512611927.apply(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_201]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[server.jar:git-Bukkit-b26fb37]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:1.8.0_201]
[20:33:17 INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:33:24 ERROR]: Encountered an unexpected exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.HashMap.resize(Unknown Source) ~[?:1.8.0_201]
        at java.util.HashMap.merge(Unknown Source) ~[?:1.8.0_201]
        at java.util.stream.Collectors.lambda$toMap$58(Unknown Source) ~[?:1.8.0_201]
        at java.util.stream.Collectors$$Lambda$13/1740223770.accept(Unknown Source) ~[?:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source) ~[?:1.8.0_201]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[?:1.8.0_201]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_201]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_201]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_201]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_201]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_201]
        at com.mojang.brigadier.tree.CommandNode.addChild(CommandNode.java:110) ~[server.jar:git-Bukkit-b26fb37]
        at com.mojang.brigadier.CommandDispatcher.register(CommandDispatcher.java:58) ~[server.jar:git-Bukkit-b26fb37]
        at org.bukkit.craftbukkit.v1_13_R2.command.BukkitCommandWrapper.register(BukkitCommandWrapper.java:31) ~[server.jar:git-Bukkit-b26fb37]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.syncCommands(CraftServer.java:400) ~[server.jar:git-Bukkit-b26fb37]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:361) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:571) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:533) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:411) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:270) ~[server.jar:git-Bukkit-b26fb37]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:676) [server.jar:git-Bukkit-b26fb37]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

It is probably caused by the chunk-unloading flag. Without the plugin and the flag the server is starting fine. Running CraftBukkit for 1.13.2 and WorldGuard 7.0.0 beta 3. Hope you can fixy this.

**Comment by isokissa3** [comment]
Fixed in c4b229e
