### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by random1167** [isokissa3/WorldGuardExtraFlagsPlugin#74]
```
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
        at net.goldtreeservers.worldguardextraflags.wg.wrappers.v7.WorldGuardSevenCommunicator.doUnloadChunkFlagCheck(WorldGuardSevenCommunicator.java:108) ~[WorldGuardExtraFlags.jar:?]
        at net.goldtreeservers.worldguardextraflags.listeners.WorldListener.onChunkUnloadEvent(WorldListener.java:34) ~[WorldGuardExtraFlags.jar:?]
        at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
        ... 11 more
[02:30:03 ERROR]: Could not pass event ChunkUnloadEvent to WorldGuardExtraFlags v4.1.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
        at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:312) [spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
        at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:287) [spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:268) [spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:952) [spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
        at net.goldtreeservers.worldguardextraflags.wg.wrappers.v7.WorldGuardSevenCommunicator.doUnloadChunkFlagCheck(WorldGuardSevenCommunicator.java:108) ~[WorldGuardExtraFlags.jar:?]
        at net.goldtreeservers.worldguardextraflags.listeners.WorldListener.onChunkUnloadEvent(WorldListener.java:34) ~[WorldGuardExtraFlags.jar:?]
        at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-e5e5c7c-c24abab]
        ... 11 more
>

```
using FAWE
spigot 1.13.2
FAWE world guard

**Comment by isokissa3** [comment]
FAWE is using older WE api which is not supported by the required WG version, 4.1.1 works with FAWE as it uses older API
