### ISSUE TITLE
[1.14.2 Paper-95] Could not pass event PortalCreateEvent to WorldGuardExtraFlags v4.1.2

### ISSUE THREAD

**Issue by Leonardo-Fiori** [isokissa3/WorldGuardExtraFlagsPlugin#80]
The server is running on paper-95, latest version.
Using latest WorldGuardExtraFlags (4.1.2)
Latest WorldGuard 7.0.1-SNAPSHOT | Bukkit-Official (7.0.1-beta-01;14e7525)

I get this exception in console as soon as i use a flint and steel to turn on the portal.. the server is not crashing. The portal then is activated.

[12:31:43 ERROR]: Could not pass event PortalCreateEvent to WorldGuardExtraFlags v4.1.2
java.lang.NoSuchMethodError: org.bukkit.event.world.PortalCreateEvent.getBlocks()Ljava/util/ArrayList;
        at net.goldtreeservers.worldguardextraflags.listeners.EntityListener.onPortalCreateEvent(EntityListener.java:24) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor272.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-95]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-95]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-95]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.BlockPortal$Shape.createPortal(BlockPortal.java:347) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.BlockPortal.a(BlockPortal.java:60) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.BlockFire.onPlace(BlockFire.java:307) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:267) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:495) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1393) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:999) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:992) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:976) ~[patched_1.14.2.jar:git-Paper-95]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.14.2.jar:git-Paper-95]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by mibby** [comment]
Paper dev 122 (Spigot 1.14.3)
WorldGuard dev 1936
WorldGuardExtraFlags dev 17

@isokissa3 Can also confirm, getting this error with 1.14.3.

```
[08:06:46] [Server thread/ERROR]: Could not pass event PortalCreateEvent to WorldGuardExtraFlags v4.1.2
java.lang.NoSuchMethodError: org.bukkit.event.world.PortalCreateEvent.getBlocks()Ljava/util/ArrayList;
	at net.goldtreeservers.worldguardextraflags.listeners.EntityListener.onPortalCreateEvent(EntityListener.java:24) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor857.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-122]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:926) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.BlockEnderPortal.a(BlockEnderPortal.java:34) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.IBlockData.a(IBlockData.java:214) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.Entity.checkBlockCollisions(Entity.java:961) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.Entity.move(Entity.java:666) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.EntityLiving.e(EntityLiving.java:2204) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.EntityHuman.e(EntityHuman.java:1480) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2555) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.EntityHuman.movementTick(EntityHuman.java:401) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2317) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:150) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:420) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:146) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:259) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1216) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-122]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Royster0** [comment]
I can confirm that this error occurs also in 1.14.4, using the latest Paper version. The plugin itself still works but this pops up everytime theres an interaction of somekind with a portal by a player. It spams the console alot too.
