### ISSUE TITLE
chunk-unload flag doesn't work

### ISSUE THREAD

**Issue by MightyW0lf** [isokissa3/WorldGuardExtraFlagsPlugin#84]
```
 [10:17:58 ERROR]: Could not pass event ChunkUnloadEvent to WorldGuardExtraFlags v4.1.2
java.lang.NoSuchMethodError: org.bukkit.event.world.ChunkUnloadEvent.setCancelled(Z)V
at net.goldtreeservers.worldguardextraflags.listeners.WorldListener.onChunkUnloadEvent(WorldListener.java:36) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor190.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-163]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-163]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-163]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.Chunk.unloadCallback(Chunk.java:675) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$null$4(PlayerChunk.java:326) ~[patched_1.14.4.jar:git-Paper-163]
at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$a$5(PlayerChunk.java:320) ~[patched_1.14.4.jar:git-Paper-163]
at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_112]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_112]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_112]
at net.minecraft.server.v1_14_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:101) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.PlayerChunk.a(PlayerChunk.java:331) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(ChunkMapDistance.java:105) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:298) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.access$200(ChunkProviderServer.java:22) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:634) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:294) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1021) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1134) ~[patched_1.14.4.jar:git-Paper-163]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-163]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

* Server: Paper 1.14.4 #163
* WorldGuard Extra Flags 4.1.2
* WorldGuard 7.0.1 Release Candidate 2
  * same error with WorldGuard 7.0.0

**Comment by isokissa3** [comment]
Update to dev build
