### ISSUE TITLE
1.15 support

### ISSUE THREAD

**Issue by kadenscott** [isokissa3/WorldGuardExtraFlagsPlugin#97]
When using Paper version 1.15, this error is thrown on startup:
```
[03:36:11 ERROR]: Error occurred while enabling WorldGuardExtraFlags v4.1.2 (Is it up to date?)
com.comphenix.protocol.reflect.FieldAccessException: No field with type java.util.Map exists in class EnumProtocol.
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:60) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:59) ~[?:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:39) ~[?:?]
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70) ~[?:?]
        at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271) ~[?:?]
        at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:259) ~[?:?]
        at com.comphenix.protocol.concurrency.PacketTypeSet.getPacketClass(PacketTypeSet.java:82) ~[?:?]
        at com.comphenix.protocol.concurrency.PacketTypeSet.addType(PacketTypeSet.java:35) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.addPacketHandler(ProtocolInjector.java:385) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.enablePacketFilters(PacketFilterManager.java:624) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:390) ~[?:?]
        at net.goldtreeservers.worldguardextraflags.protocollib.ProtocolLibHelper.onEnable(ProtocolLibHelper.java:23) ~[?:?]
        at net.goldtreeservers.worldguardextraflags.WorldGuardExtraFlagsPlugin.onEnable(WorldGuardExtraFlagsPlugin.java:166) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.jar:git-Paper-8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.jar:git-Paper-8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.jar:git-Paper-8]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.jar:git-Paper-8]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.jar:git-Paper-8]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.jar:git-Paper-8]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.jar:git-Paper-8]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.jar:git-Paper-8]
        at java.lang.Thread.run(Thread.java:835) [?:?]
```

**Comment by isokissa3** [comment]
ProtocolLib plugin is outdated
